### ISSUE TITLE
obnam importer

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg-import#13]

**Comment by carnil** [comment]
FTR, obnam upstream recently announced obnam will be retired. So having an importer for obnam made backups would really help people to migrate over to borg.

Reference: https://blog.liw.fi/posts/2017/08/13/retiring_obnam/

**Comment by ThomasWaldmann** [comment]
Yup, that would be very useful.

Maybe some obnam using Pythonista can do a PR for that?

**Comment by ThomasWaldmann** [comment]
Considering nobody did a PR yet, guess this is not needed.
