### ISSUE TITLE
get rid of python 3.4

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg-import#33]
python 3.4 is out of support, so we should drop it, too, and require py35+.

get some hints from borg master branch and do it in a similar way for borg-import:
- https://github.com/borgbackup/borg/blob/master/.travis.yml
- https://github.com/borgbackup/borg/blob/master/tox.ini

also: fix setup.py and the docs about the python requirements.

**Comment by Ankit-rana** [comment]
In addition to removing 3.4, do we also want to add 3.6,3.7 and 3.8? these are supported version for borg.

**Comment by ThomasWaldmann** [comment]
Yes, we should have py35,36,37,38.
