### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by MircoBlitz** [borgbackup/borg-import#44]
I don't find any information about it and a pip3 install borg-import crashes. \o/

**Comment by ThomasWaldmann** [comment]
I need the traceback, please.

**Comment by ThomasWaldmann** [comment]
Also, there is no release yet, thus no code on pypi.

So, the rough steps are:
- create and activate a virtualenv (recommended, but not required)
- git clone the repo to local disk
- `pip install -e .`

**Comment by gobborg** [comment]
Can this issue be closed?

**Comment by ThomasWaldmann** [comment]
yes, it is documented there: https://borg-import.readthedocs.io/en/latest/installation.html

btw, i noticed the markup there is broken, see the githubrepo link.

**Comment by gobborg** [comment]
Do you mean that the markup isn't rendering properly on GitHub? That's happening for all .rst pages that I've seen -> I think it's a GitHub problem.

**Comment by ThomasWaldmann** [comment]
No, I meant the html at the linked location in previous post.

**Comment by gobborg** [comment]
Sorry, I'm still not following.

**Comment by gobborg** [comment]
Found it and found the error. I'll fix it in my next PR.
